### ISSUE TITLE
Cl Failing because run-rs not installed welled 

### ISSUE THREAD

**Issue by dtboy1995** [ithot-all/mongoose-acid#5]
### error log
```terminal
+ run-rs@0.5.3
added 95 packages from 60 contributors in 5.419s
before_install.2
0.00s$ run-rs -v 4.0.0 &
install
6.01s$ npm install
Downloading MongoDB 4.0.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 67.3M  100 67.3M    0     0  54.8M      0  0:00:01  0:00:01 --:--:-- 54.8M
Copied MongoDB 4.0.0 to '/home/travis/.nvm/versions/node/v8.16.1/lib/node_modules/run-rs/src/4.0.0'
Purging database...
Running '/home/travis/.nvm/versions/node/v8.16.1/lib/node_modules/run-rs/4.0.0/mongod' [ 27017, 27018, 27019 ]
Starting replica set...
/home/travis/.nvm/versions/node/v8.16.1/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/replset.js:124
            .toString()
             ^
TypeError: Cannot read property 'toString' of null
    at ChildProcess.<anonymous> (/home/travis/.nvm/versions/node/v8.16.1/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/replset.js:124:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
audited 876892 packages in 5.376s
found 0 vulnerabilities
```

**Comment by dtboy1995** [comment]
fix https://github.com/vkarpov15/run-rs/issues/37
